### ISSUE TITLE
[Bug] headlessServiceEnabled incorrect in cluster samples

### ISSUE THREAD

**Issue by clettieri** [Orange-OpenSource/nifikop#17]
## Bug Report

**What did you do?**
Tried to deploy the sample cluster using the headless service spec as formatted [here](https://github.com/Orange-OpenSource/nifikop/blob/83246d004975f41897fbef699da7b48f94822df3/config/samples/tls_secured_nificluster.yaml#L6)

**What did you expect to see?**
The sample cluster to deploy.

**What did you see instead? Under which circumstances?**
An error stating `headlessServiceEnabled` must be included

**Environment**
* nifikop version:

0.2.0

**Possible Solution**
I refactored my NiFiCluster object to have a field `headlessServiceEnabled` instead of what the sample has [here](https://github.com/Orange-OpenSource/nifikop/blob/83246d004975f41897fbef699da7b48f94822df3/config/samples/tls_secured_nificluster.yaml#L6).

Looks like this is what should be in the config based on the [this line](https://github.com/Orange-OpenSource/nifikop/blob/83246d004975f41897fbef699da7b48f94822df3/helm/nifikop/templates/nifi.orange.com_nificlusters_crd.yaml#L50) in the CRD.

**Additional context**
I'm surprised no one else ran into this issue trying to create the sample?  

Seems like a simple fix to all 3 samples, just would like confirmation I'm not missing something here.

**Comment by erdrix** [comment]
Hi ! 
The field `headlessServiceEnabled` is an old one, which was used in the previous version https://github.com/Orange-OpenSource/nifikop/blob/v0.1.0-release/pkg/apis/nifi/v1alpha1/nificluster_types.go#L27

Since the version `0.2.0` we now use the field`Spec.Service.HeadlessEnabled` : https://github.com/Orange-OpenSource/nifikop/blob/v0.2.0-release/pkg/apis/nifi/v1alpha1/nificluster_types.go#L91

I think the operator you have deployed is in an old version, to quickly check which version is deployed :

```bash
kubectl get pods -l app=nifikop -o json | jq ".items[].spec.containers[].image"
```
For the lastest version you should have : `orangeopensource/nifikop:v0.2.0-release`

Can you give me the command you used to deploy it ?

**Comment by clettieri** [comment]
Hi @erdrix, appreciate the reply.

I do have `"image": "orangeopensource/nifikop:v0.2.0-release"` as the image that is deployed.

In version 0.2.0 to use the new field, wouldn't the CRD need to reflect that as well?  Currently it still shows the `headlessServiceEnabled` [here](
https://github.com/Orange-OpenSource/nifikop/blob/f063ce4001de4809f93afcf3b765cf2442dc88dd/helm/nifikop/templates/nifi.orange.com_nificlusters_crd.yaml#L50) and as a required field [here](https://github.com/Orange-OpenSource/nifikop/blob/f063ce4001de4809f93afcf3b765cf2442dc88dd/helm/nifikop/templates/nifi.orange.com_nificlusters_crd.yaml#L2295).

I appreciate the reply!

**Comment by erdrix** [comment]
I get it, we forgot to update the crd sprovided in the Helm chart, as we switched to helm 3 which doesn't support the crds installations. 

I just created a PR #18 to fix this, but I already pushed the correction into the helm repo, so if you make a : 

```bash
helm repo update
```

and upgrade or re-install the chart it should be ok, let me know if it's not :) 
If not, in the meantime, you can do the same things as for helm 3 : 

```bash 
$ kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/deploy/crds/nifi.orange.com_nificlusters_crd.yaml
$ kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/deploy/crds/nifi.orange.com_nifiusers_crd.yaml
```

**Comment by clettieri** [comment]
Having trouble pulling from the helm repo now.  The two CRD's are giving me problems after this change.

Apologies for this poor formatting, still trying to understand what the issue is here now.  Sharing in case you have a better idea.

```CustomResourceDefinition.apiextensions.k8s.io "nificlusters.nifi.orange.com" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc001a846e0), Subresources:(*apiextensions.CustomResourceSubresources)(0xc01d7f7830), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: **per-version schemas may not all be set to identical values** (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc001a846e0), Subresources:(*apiextensions.CustomResourceSubresources)(0xc01d7f7830), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]```

In the meantime, I can try to explicitly apply using the commands for helm 3.

**Comment by erdrix** [comment]
You have this issue because we use `v1` of `customresourcedefinitions` and the version of your Kubernetes cluster should be under **1.16** : https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#before-you-begin

To make it simpler, I removed the crds from chart and updated the documentation to add a step to deploy CRDs manually : https://github.com/Orange-OpenSource/nifikop/pull/18/commits/cb39fdd035635d2d84297f6954f48dd02115bea2

I also generated the CRDs in version `v1beta1` of k8s api, to make it work for kubernetes cluster whose version is under 1.16 : https://github.com/Orange-OpenSource/nifikop/pull/18/commits/186896e97934a1c9bb930c7a77ccaec1e41debed

Until we have merged this PR, you can manually deploy the correct CRDs using : 

```bash
kubectl apply -f https://raw.githubusercontent.com/erdrix/nifikop/fix_documentations/deploy/crds/v1beta1/nifi.orange.com_nificlusters_crd.yaml

kubectl apply -f https://raw.githubusercontent.com/erdrix/nifikop/fix_documentations/deploy/crds/v1beta1/nifi.orange.com_nifiusers_crd.yaml
```

**Comment by clettieri** [comment]
Thank you @erdrix!
