### ISSUE TITLE
Mounting configmaps into the pod

### ISSUE THREAD

**Issue by Arttii** [Orange-OpenSource/nifikop#32]
## Question

I was wondering is there a simple way to copy files from say a configmap into the nifi pod? I need to be able to copy a non-public root ca inside there to be able to talk my oidc provider. This does not seem to be possible right now. I think a possibility to define the volumes would address this usecase.

**Comment by erdrix** [comment]
Indeed there is no way to declare a volume mount from existing volume using the `NifiCluster` resource.
We've already thought about this use case and there are two ways to deal with it : 

1 - We are enhancing the [StorageConfig](https://github.com/Orange-OpenSource/nifikop/blob/master/pkg/apis/nifi/v1alpha1/nificluster_types.go#L223) object to support this feature.

2 -  We don't want to give such a responsability to the operator, because we think it's not something it has to handle, so you have to define a [podpreset](https://kubernetes.io/docs/concepts/workloads/pods/podpreset/) to declare that you want to mount your configmap into all nifi node's pods.

On our side we have priviledged the 2nd approach because it allows us to say : "you can define and use what the operator knows and must manage, and the things which are customized require to use other things than the operator so, be carefull of what you do !"

However, we are quite open on this topic, and if some arguements make sense to implement it ... why not :) ?

**Comment by Arttii** [comment]
Actually you are right, that would address my requirement. Thanks!

**Comment by jdesroch** [comment]
Since PodPresets are not available can this issue be reopened?  I am looking for a way to mount ConfigMaps in my NiFi nodes for additional properties files.
